name = "Coder"
license = "MIT"
licenselink = "https://github.com/luizdepra/hugo-coder/blob/master/LICENSE.md"
description = "A simple and clean blog theme for Hugo"
homepage = "https://github.com/luizdepra/hugo-coder/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.79.0"

[author]
name = "Luiz F. A. de Prá"
homepage = "https://luizdepra.com"

<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1403318151&auto=1&height=66"></iframe>